sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules
env:
  global:
  - ENCRYPTION_LABEL: "d1139ddcac92"
  - COMMIT_AUTHOR_EMAIL: "bartvde@boundlessgeo.com"

before_install:
  - "npm prune"

before_script:
  - "export DISPLAY=:99.0"

script:
  - "npm run test"

after_success:
  - "bash ./deploy.sh"
  - "npm run cover"
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
